export enum ActionType {
    MOVE_ELEMENTS = 'MOVE_ELEMENTS',
    RESIZE_ELEMENTS = 'RESIZE_ELEMENTS',
    SET_SELECTION = 'SET_SELECTION',
    SET_ACTIVE_SLIDE = 'SET_ACTIVE_SLIDE',
    ADD_SLIDE = 'ADD_SLIDE',
    DELETE_SLIDE = 'DELETE_SLIDE',
    ADD_IMAGE = 'ADD_IMAGE',
    SET_TEXT_PROPERTY = 'SET_TEXT_PROPERTY',
    FONT_SIZE_INC_DEC = 'FONT_SIZE_INC_DEC',
    SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR',
}